<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="TestSystemDemo-20180719153610" skipped="0" tests="2" time="57.943" timestamp="2018-07-19T15:37:08">
	<testcase classname="TestSystemDemo" name="test_system_login" time="11.378" timestamp="2018-07-19T15:37:08"/>
	<testcase classname="TestSystemDemo" name="test_create_client" time="46.565" timestamp="2018-07-19T15:36:57">
		<error message="Message: 
" type="TimeoutException">
<![CDATA[Traceback (most recent call last):
  File ".\DemoSystemTests.py", line 133, in test_create_client
    wait.until(EC.presence_of_element_located((By.XPATH, '/html/body/div/table/tbody')))
  File "C:\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[Client creation failed!
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
